# Generated by Django 4.1.7 on 2023-04-27 17:54

from django.db import migrations, models
import django.db.models.deletion
import gestaoPedidos.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoPedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anolecionada', models.CharField(db_column='AnoLecionada', max_length=255, validators=[gestaoPedidos.models.year_validator])),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidouc',
            name='inst_disciplina',
        ),
        migrations.RemoveField(
            model_name='pedidouc',
            name='turma',
        ),
        migrations.AddField(
            model_name='pedidouc',
            name='curso',
            field=models.CharField(db_column='Curso', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidouc',
            name='regente',
            field=models.CharField(db_column='Regente', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estadoid',
            field=models.ForeignKey(db_column='EstadoID', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedidouc',
            name='anolecionada',
            field=models.CharField(choices=[('2023', '2023')], db_column='AnoLecionada', max_length=255, validators=[gestaoPedidos.models.year_validator]),
        ),
        migrations.AlterField(
            model_name='pedidouc',
            name='data_fim',
            field=models.CharField(db_column='Data_Fim', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidouc',
            name='data_inicio',
            field=models.CharField(db_column='Data_Inicio', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidouc',
            name='dataalterar',
            field=models.IntegerField(blank=True, db_column='DataAlterar', default='', null=True),
        ),
        migrations.AlterField(
            model_name='pedidouc',
            name='datanova',
            field=models.IntegerField(blank=True, db_column='DataNova', default='', null=True),
        ),
        migrations.AlterField(
            model_name='pedidouc',
            name='horas_periodo',
            field=models.CharField(db_column='Horas_Periodo', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidouc',
            name='horas_semanais',
            field=models.CharField(db_column='Horas_semanais', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidouc',
            name='id_uc',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pedidouc',
            name='motivopedido',
            field=models.CharField(blank=True, db_column='MotivoPedido', default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedidouc',
            name='nomeuc',
            field=models.CharField(db_column='NomeUC', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidouc',
            name='semestrelecionada',
            field=models.CharField(choices=[('1semestre', '1º Semestre'), ('2semestre', '2º Semestre')], db_column='SemestreLecionada', default='', max_length=255),
        ),
    ]
