# Generated by Django 4.1.7 on 2023-04-27 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao', max_length=255)),
            ],
            options={
                'db_table': 'campus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('codigo_curso', models.IntegerField(db_column='Codigo_Curso')),
            ],
            options={
                'db_table': 'curso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao', max_length=255)),
            ],
            options={
                'db_table': 'estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoSala',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao', max_length=255)),
            ],
            options={
                'db_table': 'estado_sala',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hora', models.DateField(db_column='Hora')),
                ('diasemana', models.CharField(db_column='DiaSemana', max_length=255)),
                ('descricao', models.CharField(db_column='Descricao', max_length=255)),
            ],
            options={
                'db_table': 'horario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dataAlvo', models.DateField(db_column='dataAlvo', verbose_name='Data Alvo')),
                ('assunto', models.CharField(db_column='assunto', max_length=255, verbose_name='Assunto')),
                ('descricao', models.TextField(db_column='descricao', max_length=255, verbose_name='Descrição')),
                ('datecreation', models.DateField(db_column='DateCreation')),
                ('datevalidation', models.DateField(db_column='DateValidation', null=True)),
                ('estadoid', models.ForeignKey(db_column='EstadoID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.estado', verbose_name='Estado')),
            ],
            options={
                'db_table': 'pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('sexo', models.CharField(db_column='Sexo', max_length=255)),
                ('data_nascimento', models.CharField(db_column='Data_Nascimento', max_length=255)),
                ('ativo', models.TextField(db_column='Ativo')),
                ('nacionalidade', models.IntegerField(db_column='Nacionalidade')),
                ('data_emissao_identificacao', models.CharField(db_column='Data_emissao_identificacao', max_length=255)),
                ('data_validade_identificacao', models.CharField(db_column='Data_validade_Identificacao', max_length=255)),
                ('nif', models.IntegerField(db_column='NIF')),
                ('pais_fiscal', models.IntegerField(db_column='Pais_Fiscal')),
                ('tipo_identificacao', models.IntegerField(db_column='Tipo_Identificacao')),
                ('digito_verificacao', models.SmallIntegerField(db_column='Digito_verificacao')),
                ('identificacao', models.CharField(db_column='Identificacao', max_length=255)),
                ('user', models.ForeignKey(blank=True, db_column='user', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipoalteracao',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao', max_length=255)),
            ],
            options={
                'db_table': 'tipoalteracao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoSala',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao', max_length=255)),
            ],
            options={
                'db_table': 'tipo_sala',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UC',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('semestre_lecionada', models.IntegerField(db_column='SemestreLecionada')),
                ('codigo_disciplina', models.IntegerField(db_column='Codigo_disciplina')),
                ('nomeuc', models.CharField(db_column='NomeUC', max_length=255)),
                ('instituicao_disciplina', models.CharField(db_column='Inst_disciplina', max_length=255)),
                ('turma', models.CharField(db_column='Turma', max_length=255)),
                ('ano_lecionada', models.IntegerField(db_column='AnoLecionada')),
                ('horas_semanais', models.CharField(db_column='Horas_semanais', max_length=255)),
                ('horas_periodo', models.CharField(db_column='Horas_Periodo', max_length=255)),
                ('data_inicio', models.CharField(db_column='Data_Inicio', max_length=255)),
                ('data_fim', models.CharField(db_column='Data_Fim', max_length=255)),
            ],
            options={
                'db_table': 'uc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('codigo_docente', models.IntegerField(db_column='Codigo_Docente')),
                ('departamento_docente', models.CharField(db_column='Departamento_Docente', max_length=255)),
                ('num_individuo', models.IntegerField(db_column='Num_Individuo')),
                ('arquivo', models.TextField(db_column='Arquivo')),
                ('pessoaid', models.OneToOneField(db_column='PessoaID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestaoPedidos.pessoa')),
                ('cursoid', models.ForeignKey(db_column='CursoID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.curso')),
            ],
            options={
                'db_table': 'docente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('nfunc', models.IntegerField(db_column='NFunc')),
                ('pessoaid', models.OneToOneField(db_column='PessoaID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestaoPedidos.pessoa')),
            ],
            options={
                'db_table': 'funcionario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Outros',
            fields=[
                ('descricao', models.CharField(db_column='Descricao', max_length=255)),
                ('data', models.CharField(db_column='Data', max_length=255)),
                ('numero_alunos_previstos', models.IntegerField(db_column='Numero_alunos_previstos')),
                ('duracao_prova', models.CharField(db_column='Duracao_prova', max_length=255)),
                ('pedidoid', models.OneToOneField(db_column='PedidoID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestaoPedidos.pedido')),
            ],
            options={
                'db_table': 'outros',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PedidoSala',
            fields=[
                ('pedidoid', models.OneToOneField(db_column='PedidoID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestaoPedidos.pedido')),
                ('motivopedido', models.CharField(db_column='MotivoPedido', max_length=255)),
                ('dataalterar', models.DateField(db_column='DataAlterar')),
                ('datanova', models.DateField(db_column='DataNova')),
            ],
            options={
                'db_table': 'pedido_sala',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PedidoUC',
            fields=[
                ('pedidoid', models.OneToOneField(db_column='PedidoID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestaoPedidos.pedido')),
                ('motivopedido', models.CharField(blank=True, db_column='MotivoPedido', max_length=255, null=True)),
                ('dataalterar', models.IntegerField(blank=True, db_column='DataAlterar', null=True)),
                ('datanova', models.IntegerField(blank=True, db_column='DataNova', null=True)),
                ('id_uc', models.IntegerField(null=True)),
                ('semestrelecionada', models.CharField(db_column='SemestreLecionada', max_length=255)),
                ('nomeuc', models.CharField(db_column='NomeUC', max_length=255)),
                ('inst_disciplina', models.CharField(db_column='Inst_disciplina', max_length=255)),
                ('turma', models.CharField(db_column='Turma', max_length=255)),
                ('anolecionada', models.IntegerField(db_column='AnoLecionada')),
                ('horas_semanais', models.CharField(db_column='Horas_semanais', max_length=255)),
                ('horas_periodo', models.CharField(db_column='Horas_Periodo', max_length=255)),
                ('data_inicio', models.CharField(db_column='Data_Inicio', max_length=255)),
                ('data_fim', models.CharField(db_column='Data_Fim', max_length=255)),
            ],
            options={
                'db_table': 'pedido_uc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estadouc',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao', max_length=255)),
                ('ucid', models.ForeignKey(db_column='UCID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.uc')),
            ],
            options={
                'db_table': 'estadouc',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='uc',
            name='pedido_uc',
            field=models.ForeignKey(db_column='Pedido_UCPedidoID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.pedidouc'),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('num', models.FloatField(db_column='Num')),
                ('edificio', models.IntegerField(db_column='Edificio')),
                ('capacidade', models.IntegerField(db_column='capacidade')),
                ('campusid', models.ForeignKey(db_column='CampusID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.campus')),
                ('estado_salaid', models.ForeignKey(db_column='Estado_SalaID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.estadosala')),
                ('tipo_salaid', models.ForeignKey(db_column='Tipo_SalaID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.tiposala')),
                ('pedido_salapedidoid', models.ForeignKey(db_column='Pedido_SalaPedidoID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.pedidosala')),
            ],
            options={
                'db_table': 'sala',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pedidosala',
            name='id_sala',
            field=models.ForeignKey(db_column='id_sala', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.sala'),
        ),
        migrations.CreateModel(
            name='PedidoHorario',
            fields=[
                ('motivopedido', models.CharField(db_column='MotivoPedido', max_length=255, verbose_name='Motivo do Pedido')),
                ('dataalterar', models.IntegerField(db_column='DataAlterar')),
                ('datanova', models.IntegerField(db_column='DataNova')),
                ('pedidoid', models.OneToOneField(db_column='PedidoID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestaoPedidos.pedido')),
                ('horarioid', models.ForeignKey(db_column='HorarioID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='horarioid', to='gestaoPedidos.horario')),
                ('horarioid2', models.ForeignKey(db_column='HorarioID2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='horarioid2', to='gestaoPedidos.horario')),
                ('tipoalteracaoid', models.ForeignKey(db_column='TipoAlteracaoID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.tipoalteracao', verbose_name='Tipo de Alteração')),
                ('unidadec', models.ForeignKey(db_column='UnidadeC', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.uc', verbose_name='Unidade Curricular')),
            ],
            options={
                'db_table': 'pedido_horario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='docentepessoaid',
            field=models.ForeignKey(db_column='DocentePessoaID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.docente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='funcionariopessoaid',
            field=models.ForeignKey(db_column='FuncionarioPessoaID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.funcionario'),
        ),
        migrations.AddField(
            model_name='docente',
            name='ucid',
            field=models.ForeignKey(db_column='UCID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.uc'),
        ),
        migrations.CreateModel(
            name='CursoUc',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cursoid', models.OneToOneField(db_column='CursoID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.curso')),
                ('ucid', models.OneToOneField(db_column='UCID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.uc')),
            ],
            options={
                'db_table': 'curso_uc',
                'managed': True,
                'unique_together': {('cursoid', 'ucid')},
            },
        ),
    ]
