# Generated by Django 4.1.7 on 2023-04-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoPedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uc',
            old_name='anolecionada',
            new_name='ano_lecionada',
        ),
        migrations.RenameField(
            model_name='uc',
            old_name='inst_disciplina',
            new_name='instituicao_disciplina',
        ),
        migrations.RenameField(
            model_name='uc',
            old_name='pedido_ucpedidoid',
            new_name='pedido_uc',
        ),
        migrations.RenameField(
            model_name='uc',
            old_name='semestrelecionada',
            new_name='semestre_lecionada',
        ),
    ]
