# Generated by Django 4.1.7 on 2023-04-17 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uc',
            name='motivopedido',
            field=models.CharField(db_column='MotivoPedido', default='', max_length=255, verbose_name='Motivo do Pedido'),
        ),
        migrations.AddField(
            model_name='uc',
            name='tipoalteracaoid',
            field=models.ForeignKey(db_column='TipoAlteracaoID', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.tipoalteracao', verbose_name='Tipo de Alteração'),
        ),
    ]
