# Generated by Django 4.1.7 on 2023-04-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoPedidos', '0002_rename_anolecionada_uc_ano_lecionada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uc',
            name='pedido_uc',
            field=models.ForeignKey(db_column='PedidoID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoPedidos.pedidouc'),
        ),
    ]
