# Generated by Django 4.1.7 on 2023-03-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilizadores', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='pessoaid',
        ),
        migrations.AlterField(
            model_name='docenteuc',
            name='docentepessoaid',
            field=models.OneToOneField(db_column='DocentePessoaID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='utilizadores.docente'),
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
